# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blick < Formula
  desc "Check Microsoft 365 mail, Teams chats, and next meeting from the terminal"
  homepage "https://excelano.com/blick-cli/"
  version "0.12.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/blick-cli/releases/download/v0.12.3/blick_0.12.3_darwin_amd64.tar.gz"
      sha256 "f1f0a9df4d472eab57d5c7f9b272dfdf8498abff9f5256e5c31fcf8c7921360f"

      define_method(:install) do
        bin.install "blick"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/blick-cli/releases/download/v0.12.3/blick_0.12.3_darwin_arm64.tar.gz"
      sha256 "6734bdb0e4c8a775cd68b48bf21db6c19ceedbc4f5e17e7fc1d2868c886debfd"

      define_method(:install) do
        bin.install "blick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/blick-cli/releases/download/v0.12.3/blick_0.12.3_linux_amd64.tar.gz"
      sha256 "4e1aa640b53b2ed5efe8136fee09448cf2b4c17b390af92987ed42275a9ffc38"
      define_method(:install) do
        bin.install "blick"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/blick-cli/releases/download/v0.12.3/blick_0.12.3_linux_arm64.tar.gz"
      sha256 "df5acb5defdc295ae0cdde38ac04bf492b6f77783e8dd36be034e50c739bde44"
      define_method(:install) do
        bin.install "blick"
      end
    end
  end

  test do
    system "#{bin}/blick", "--version"
  end
end
