# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blick < Formula
  desc "Check Microsoft 365 mail, Teams chats, and next meeting from the terminal"
  homepage "https://excelano.com/blick-cli/"
  version "0.9.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/blick-cli/releases/download/v0.9.3/blick_0.9.3_darwin_amd64.tar.gz"
      sha256 "c4f906ad1c999810f1ff32bb05a33697330423cd70d9d1e2e95a987edd821959"

      define_method(:install) do
        bin.install "blick"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/blick-cli/releases/download/v0.9.3/blick_0.9.3_darwin_arm64.tar.gz"
      sha256 "7ad4c361e696d5e04ad6d4d09bd39c3aff7f31e8fbdd082674039a2f11ecf68b"

      define_method(:install) do
        bin.install "blick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/blick-cli/releases/download/v0.9.3/blick_0.9.3_linux_amd64.tar.gz"
      sha256 "9d2f7c6c49d4c4ec0259a76af9bc63d80bde24d0654a5e5ede948242a7feecfd"
      define_method(:install) do
        bin.install "blick"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/blick-cli/releases/download/v0.9.3/blick_0.9.3_linux_arm64.tar.gz"
      sha256 "4221829794f328988ab76ef56ade96d9b634080c1dd4db5d95480ae4837d48a3"
      define_method(:install) do
        bin.install "blick"
      end
    end
  end

  test do
    system "#{bin}/blick", "--version"
  end
end
