# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blick < Formula
  desc "Check Microsoft 365 mail, Teams chats, and next meeting from the terminal"
  homepage "https://excelano.com/blick-cli/"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/blick-cli/releases/download/v0.12.0/blick_0.12.0_darwin_amd64.tar.gz"
      sha256 "f3a0653eb9bcf52a2d6b500cb8f13c36d17f2b8acc5b4890f50ad8149ba502f3"

      define_method(:install) do
        bin.install "blick"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/blick-cli/releases/download/v0.12.0/blick_0.12.0_darwin_arm64.tar.gz"
      sha256 "1668f1cac07d9ee6e88ccb3cbf6f037ac7909bb711027c06f3578ec92ffdd2b0"

      define_method(:install) do
        bin.install "blick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/blick-cli/releases/download/v0.12.0/blick_0.12.0_linux_amd64.tar.gz"
      sha256 "29547ad7b9ef191f695a6c6231d3f950c38f5f065c9df33a2482ed7133e733c1"
      define_method(:install) do
        bin.install "blick"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/blick-cli/releases/download/v0.12.0/blick_0.12.0_linux_arm64.tar.gz"
      sha256 "269db8289c9cc6cf35231f0fed4205b85086febc14fce7b451f14b4614d0e3a5"
      define_method(:install) do
        bin.install "blick"
      end
    end
  end

  test do
    system "#{bin}/blick", "--version"
  end
end
