# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nved < Formula
  desc "Terminal text editor that edits in your scrollback like a REPL"
  homepage "https://excelano.com/nved/"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/nved/releases/download/v1.5.0/nved_1.5.0_darwin_amd64.tar.gz"
      sha256 "2534a69529b0fef6e0eeb3f7114869f09939200c58023b00d11018a4a05f536d"

      define_method(:install) do
        bin.install "nved"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/nved/releases/download/v1.5.0/nved_1.5.0_darwin_arm64.tar.gz"
      sha256 "290c9489f9e4ba9fa4adf6c63847fa64dabfc74eac77f4ab9f4a641890e03864"

      define_method(:install) do
        bin.install "nved"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/nved/releases/download/v1.5.0/nved_1.5.0_linux_amd64.tar.gz"
      sha256 "4d34b46ede7432e629746eefa24f2e44ca0dbc3d8faf9c126c150e24eb6db747"
      define_method(:install) do
        bin.install "nved"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/nved/releases/download/v1.5.0/nved_1.5.0_linux_arm64.tar.gz"
      sha256 "76b8106a23740c43171c2402d1e63fac765200f6d82e7ae1286e8622c2582f8c"
      define_method(:install) do
        bin.install "nved"
      end
    end
  end

  test do
    system "#{bin}/nved", "--version"
  end
end
