# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xcp < Formula
  desc "Copy files to and from SharePoint document libraries, like cp"
  homepage "https://excelano.com/xftp/"
  version "1.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.1/xcp_1.10.1_darwin_amd64.tar.gz"
      sha256 "3ad006d093876f9dee8e438d47a93bb345b05731aef46a484a0c468dc5971f7d"

      define_method(:install) do
        bin.install "xcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.1/xcp_1.10.1_darwin_arm64.tar.gz"
      sha256 "59b3e848af92d264e3000ba5b4f581818d4061ead69584ad596483e8550a99b9"

      define_method(:install) do
        bin.install "xcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.1/xcp_1.10.1_linux_amd64.tar.gz"
      sha256 "1fdb2b62351e51f32554c124b94dc0102fec60647b7db82fec6b875acc34402e"
      define_method(:install) do
        bin.install "xcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.1/xcp_1.10.1_linux_arm64.tar.gz"
      sha256 "902356ab2b960bae4f1a7afe905f847114e8ffe9d8cae2b5a253d09eb8f455ab"
      define_method(:install) do
        bin.install "xcp"
      end
    end
  end

  test do
    system "#{bin}/xcp", "--version"
  end
end
