# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xfind < Formula
  desc "Find files in SharePoint document libraries, like find"
  homepage "https://excelano.com/xftp/"
  version "1.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.0/xfind_1.10.0_darwin_amd64.tar.gz"
      sha256 "964b6442f0fe612ce6bf85770981c2d2b56154b038df155508c4adcaae4273f2"

      define_method(:install) do
        bin.install "xfind"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.0/xfind_1.10.0_darwin_arm64.tar.gz"
      sha256 "7143658ffe11dc75e903974cc66885723729d79dc26bb3cc00787f233aa295da"

      define_method(:install) do
        bin.install "xfind"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.0/xfind_1.10.0_linux_amd64.tar.gz"
      sha256 "6f143e6ef081f89facb7762a8ad8696859db17f9f944fdf52d5c54f997419709"
      define_method(:install) do
        bin.install "xfind"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.0/xfind_1.10.0_linux_arm64.tar.gz"
      sha256 "fc024aba6e6b734e7f5cd7c1caded452f98cb60e650c0501d949f72fc52350a1"
      define_method(:install) do
        bin.install "xfind"
      end
    end
  end

  test do
    system "#{bin}/xfind", "--version"
  end
end
