# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xfind < Formula
  desc "Find files in SharePoint document libraries, like find"
  homepage "https://excelano.com/xftp/"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/xfiles/releases/download/v1.7.0/xfind_1.7.0_darwin_amd64.tar.gz"
      sha256 "8878b9b38a682d57fddb27cc1bee247bf89be9cf3a164b51feb59c4c9e4df6dd"

      define_method(:install) do
        bin.install "xfind"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/xfiles/releases/download/v1.7.0/xfind_1.7.0_darwin_arm64.tar.gz"
      sha256 "66354e5499eeb5b9a4d45600d6533aab14d5c5912e69729ebadac33406b7372a"

      define_method(:install) do
        bin.install "xfind"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.7.0/xfind_1.7.0_linux_amd64.tar.gz"
      sha256 "d71ae052877c79fb7e10f152f86a6d3ca48742a6e123c6264c76427fb02de299"
      define_method(:install) do
        bin.install "xfind"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.7.0/xfind_1.7.0_linux_arm64.tar.gz"
      sha256 "a78df999d95572d2cf2c1d85922689e09585cd2ab0aeef7691cfbcaf22f0ab63"
      define_method(:install) do
        bin.install "xfind"
      end
    end
  end

  test do
    system "#{bin}/xfind", "--version"
  end
end
