# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xfind < Formula
  desc "Find files in SharePoint document libraries, like find"
  homepage "https://excelano.com/xftp/"
  version "1.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.2/xfind_1.5.2_darwin_amd64.tar.gz"
      sha256 "8073c52ea8b7aa19053b3255e772a79c6d3c1900d1aed5220836c47b5fdcc8eb"

      define_method(:install) do
        bin.install "xfind"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.2/xfind_1.5.2_darwin_arm64.tar.gz"
      sha256 "22be141db61db6f9e50306b9a08b38c13bc8683b3dce10dbd32a5dcf600e74b0"

      define_method(:install) do
        bin.install "xfind"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.2/xfind_1.5.2_linux_amd64.tar.gz"
      sha256 "4ba8d1d595453df7b474456f3044f6cad0898cc42a4ec734169af87b0902ed9b"
      define_method(:install) do
        bin.install "xfind"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.2/xfind_1.5.2_linux_arm64.tar.gz"
      sha256 "a0cdfdbe51e4b516090ca9906558a344e4db7513013092d0a763563983b31060"
      define_method(:install) do
        bin.install "xfind"
      end
    end
  end

  test do
    system "#{bin}/xfind", "--version"
  end
end
