# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xftp < Formula
  desc "FTP-style interactive client for SharePoint document libraries"
  homepage "https://excelano.com/xftp/"
  version "1.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/xfiles/releases/download/v1.9.0/xftp_1.9.0_darwin_amd64.tar.gz"
      sha256 "f08aa75165948059e65b3e1e33d22ef177e5b8b5c4d96594cb65cada50e6bc99"

      define_method(:install) do
        bin.install "xftp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/xfiles/releases/download/v1.9.0/xftp_1.9.0_darwin_arm64.tar.gz"
      sha256 "aebff35dca8c9460a226383a00b98060bf0d30e40503dc47aa1d0bf19cf1ce4d"

      define_method(:install) do
        bin.install "xftp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.9.0/xftp_1.9.0_linux_amd64.tar.gz"
      sha256 "f5683e00412801f525e80a17f55376a7835571ee8fd60e03a13d2220db22d59d"
      define_method(:install) do
        bin.install "xftp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.9.0/xftp_1.9.0_linux_arm64.tar.gz"
      sha256 "70008ce0d2d0bc778f8b32585654e127704892f14e4b84d6bdb3b4c22653af57"
      define_method(:install) do
        bin.install "xftp"
      end
    end
  end

  test do
    system "#{bin}/xftp", "--version"
  end
end
