# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xftp < Formula
  desc "FTP-style interactive client for SharePoint document libraries"
  homepage "https://excelano.com/xftp/"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/xfiles/releases/download/v1.7.0/xftp_1.7.0_darwin_amd64.tar.gz"
      sha256 "e6ddd21531043876fd05ebd28f36df4268cfc14e4ffb5fbbd6590f20459e8e42"

      define_method(:install) do
        bin.install "xftp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/xfiles/releases/download/v1.7.0/xftp_1.7.0_darwin_arm64.tar.gz"
      sha256 "be775bdf97a14410fe60ff34fcf50e0c49e8de22caf2fb030e5780f2624efbc4"

      define_method(:install) do
        bin.install "xftp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.7.0/xftp_1.7.0_linux_amd64.tar.gz"
      sha256 "eb54c4bcc1f3433f5c44280e0e51ba07e052b2d62385138376bbe3d2024fff35"
      define_method(:install) do
        bin.install "xftp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.7.0/xftp_1.7.0_linux_arm64.tar.gz"
      sha256 "ed2f925e9909a5f6c79c74a16dc814f06a785f4aa02b042940a126792a56ed2f"
      define_method(:install) do
        bin.install "xftp"
      end
    end
  end

  test do
    system "#{bin}/xftp", "--version"
  end
end
