# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xql < Formula
  desc "Run real SQL against SharePoint Lists and CSV files"
  homepage "https://excelano.com/xql/"
  version "1.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/xql/releases/download/v1.8.1/xql_1.8.1_darwin_amd64.tar.gz"
      sha256 "aa7043863694750f230e655b02b5c35a9ee3b75b9ad4730f970d8727fd8be90a"

      define_method(:install) do
        bin.install "xql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/xql/releases/download/v1.8.1/xql_1.8.1_darwin_arm64.tar.gz"
      sha256 "77d456cdfa88ec284a66697cca2e98af125bc0b47f08b44d9e163fc16c66e5c7"

      define_method(:install) do
        bin.install "xql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xql/releases/download/v1.8.1/xql_1.8.1_linux_amd64.tar.gz"
      sha256 "d3423dd02be7f11771244154121eb0f99c24cb92f882435846c38e817912a89b"
      define_method(:install) do
        bin.install "xql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xql/releases/download/v1.8.1/xql_1.8.1_linux_arm64.tar.gz"
      sha256 "68ce7121d982357adee3791cdae8941c25dbe5eee83f37e3483aa320b54c3e52"
      define_method(:install) do
        bin.install "xql"
      end
    end
  end

  test do
    system "#{bin}/xql", "--version"
  end
end
