# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xql < Formula
  desc "Run real SQL against SharePoint Lists and CSV files"
  homepage "https://excelano.com/xql/"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/xql/releases/download/v1.7.0/xql_1.7.0_darwin_amd64.tar.gz"
      sha256 "aecb0e89af8d475364fd85e79e34c4c3df404cfea37b461e3fd454f28b2a5939"

      define_method(:install) do
        bin.install "xql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/xql/releases/download/v1.7.0/xql_1.7.0_darwin_arm64.tar.gz"
      sha256 "4131f9464a53de75587ff2e126e45fe6c02bf3b144375c43cfe1a0c5c05b45fe"

      define_method(:install) do
        bin.install "xql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xql/releases/download/v1.7.0/xql_1.7.0_linux_amd64.tar.gz"
      sha256 "ade62d7fbe76cf36eef3a85c31d21fedeb2d418c3c499a646f75334fccbea491"
      define_method(:install) do
        bin.install "xql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xql/releases/download/v1.7.0/xql_1.7.0_linux_arm64.tar.gz"
      sha256 "9a92edf83d720b7cb1ca9aea26d34380f1d889a5958845c7cf7c6529d624d25a"
      define_method(:install) do
        bin.install "xql"
      end
    end
  end

  test do
    system "#{bin}/xql", "--version"
  end
end
