# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xsync < Formula
  desc "Sync local directories with SharePoint document libraries"
  homepage "https://excelano.com/xftp/"
  version "1.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.1/xsync_1.5.1_darwin_amd64.tar.gz"
      sha256 "f2739baa42c2196a7e01433372c3473ef24d8e355d4f69bf5acbde82141c5cb5"

      define_method(:install) do
        bin.install "xsync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.1/xsync_1.5.1_darwin_arm64.tar.gz"
      sha256 "eebf2b85d871fe1fe795b079d211dcf53fcecea088743898ca960ceff012838d"

      define_method(:install) do
        bin.install "xsync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.1/xsync_1.5.1_linux_amd64.tar.gz"
      sha256 "dc406cb4a0e50f6d87cc13cbff49c5644d836c4a1e7eaa88cfa7ed4fa87ab8f0"
      define_method(:install) do
        bin.install "xsync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.1/xsync_1.5.1_linux_arm64.tar.gz"
      sha256 "3d598fb6f432b17581038575b316ba4eb6ddad1314ff24f7d038aa51daad55fe"
      define_method(:install) do
        bin.install "xsync"
      end
    end
  end

  test do
    system "#{bin}/xsync", "--version"
  end
end
