# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xtree < Formula
  desc "Show SharePoint document libraries as a tree, like tree"
  homepage "https://excelano.com/xftp/"
  version "1.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.1/xtree_1.10.1_darwin_amd64.tar.gz"
      sha256 "a3326bebee06f7c7494dbd914a81ea36044e454d162cd985ed96840a82dd6b42"

      define_method(:install) do
        bin.install "xtree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.1/xtree_1.10.1_darwin_arm64.tar.gz"
      sha256 "de779665aa0fc3a044f391f5a97489526fbf16eeffabe9a91d243ab04f82b567"

      define_method(:install) do
        bin.install "xtree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.1/xtree_1.10.1_linux_amd64.tar.gz"
      sha256 "22e6c785c57d89869aa6d9e5e09b22d62cbf608336a72df03e6c5d3016a0e373"
      define_method(:install) do
        bin.install "xtree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.10.1/xtree_1.10.1_linux_arm64.tar.gz"
      sha256 "6d4135faddbcea371f78c1bdd8d95830b47451ce57858bed7fa556226e57fdef"
      define_method(:install) do
        bin.install "xtree"
      end
    end
  end

  test do
    system "#{bin}/xtree", "--version"
  end
end
