# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xtree < Formula
  desc "Show SharePoint document libraries as a tree, like tree"
  homepage "https://excelano.com/xftp/"
  version "1.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.1/xtree_1.5.1_darwin_amd64.tar.gz"
      sha256 "6aaee738fc49403f4fdf33252dacb1746d325b9c9bd755b67e85ad94102e90f5"

      define_method(:install) do
        bin.install "xtree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.1/xtree_1.5.1_darwin_arm64.tar.gz"
      sha256 "a668c89e80aca03ee33390a244d2a248bbcf99678a91fd43bd5d97216614f2a7"

      define_method(:install) do
        bin.install "xtree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.1/xtree_1.5.1_linux_amd64.tar.gz"
      sha256 "9ddffe9f2401d3660cd96fc79bebfd3be1ba719107006df62d934873ece4337f"
      define_method(:install) do
        bin.install "xtree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/excelano/xfiles/releases/download/v1.5.1/xtree_1.5.1_linux_arm64.tar.gz"
      sha256 "e3378943a94a221bb51799fb8d94caabcef1bb7652d07ac57ce7992e277940a4"
      define_method(:install) do
        bin.install "xtree"
      end
    end
  end

  test do
    system "#{bin}/xtree", "--version"
  end
end
